language: cpp

compiler:
    - gcc
    - clang

script:
    - cd build
    - cmake ../src -DCMAKE_C_FLAGS="-I/usr/include/freetype2"
    - make VERBOSE=1
    - ./narfblock-test

before_install:
    - sudo ./travis-setup.sh

notifications:
    irc:
        channels:
            - "chat.freenode.net#narfblock"
