language: cpp

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

matrix:
    exclude:
        - os: osx
          compiler: gcc

script:
    - cd build
    - cmake ../src -DCMAKE_C_FLAGS="-I/usr/include/freetype2"
    - make VERBOSE=1
    - ./narfblock-test

before_install:
    - "if [ $(uname) = Linux ]; then sudo travis/setup-linux.sh; fi"
    - "if [ $(uname) = Darwin ]; then travis/setup-osx.sh; fi"

notifications:
    irc:
        channels:
            - "chat.freenode.net#narfblock"
