language: cpp

compiler:
    - gcc
    - clang

script:
    - cd build
    - cmake ../src -DCMAKE_C_FLAGS="-I/usr/include/freetype2"
    - make VERBOSE=1

before_install:
    - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake libsdl2-dev libpng12-dev zlib1g-dev libglew-dev libfreetype6-dev libncurses5-dev libenet-dev
    - sudo apt-get install g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo apt-get install -y libgtest-dev
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

notifications:
    irc:
        channels:
            - "chat.freenode.net#narfblock"
