language: cpp

dist: trusty
sudo: false

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - cmake
            - libsdl2-dev
            - libpng12-dev
            - zlib1g-dev
            - libfreetype6-dev
            - libncurses5-dev
            - libenet-dev
            - libogg-dev
            - libopus-dev
            - libopusfile-dev
            - libgtest-dev

os:
    - linux
    - osx

matrix:
    exclude:
        - os: osx
          compiler: gcc
        - os: linux
          compiler: clang

script:
    - cd build
    - cmake ../src -DCMAKE_C_FLAGS="-I/usr/include/freetype2"
    - make VERBOSE=1
    - ./lib/narflib-test
    - ./narfblock-test

before_install:
    - "if [ $(uname) = Darwin ]; then travis/setup-osx.sh; fi"

notifications:
    irc:
        channels:
            - "chat.freenode.net#narfblock"
