language: cpp

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

matrix:
    exclude:
        - os: osx
          compiler: gcc
    allow_failures:
        - os: osx

script:
    - cd build
    - cmake ../src -DCMAKE_C_FLAGS="-I/usr/include/freetype2"
    - make VERBOSE=1
    - ./narfblock-test

before_install:
    - ./travis-setup.sh

notifications:
    irc:
        channels:
            - "chat.freenode.net#narfblock"
