language: cpp
compiler:
    - gcc
    - clang
script: cd build && cmake ../src && make
before_install:
    - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake libsdl2-dev libpng12-dev zlib1g-dev libglew-dev libfreetype6-dev libncurses5-dev libenet-dev
    - sudo apt-get install g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo ln -s /usr/include/freetype2/freetype /usr/include/freetype2/freetype/freetype

notifications:
    irc:
        channels:
            - "chat.freenode.net#narfblock"
