FIND_PATH(OpusFile_INCLUDE_DIR opusfile.h PATH_SUFFIXES include/opus include)
FIND_LIBRARY(OpusFile_LIBRARY NAMES opusfile PATH_SUFFIXES lib lib64)

SET(OpusFile_INCLUDE_DIRS ${OpusFile_INCLUDE_DIR})
SET(OpusFile_LIBRARIES ${OpusFile_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpusFile
    REQUIRED_VARS OpusFile_LIBRARY OpusFile_INCLUDE_DIRS)

MARK_AS_ADVANCED(OpusFile_INCLUDE_DIR OpusFile_LIBRARY)
