FIND_PATH(Opus_INCLUDE_DIR opus.h PATH_SUFFIXES include/opus include)
FIND_LIBRARY(Opus_LIBRARY NAMES opus PATH_SUFFIXES lib lib64)

SET(Opus_INCLUDE_DIRS ${Opus_INCLUDE_DIR})
SET(Opus_LIBRARIES ${Opus_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Opus
                                  REQUIRED_VARS Opus_LIBRARY Opus_INCLUDE_DIRS)

MARK_AS_ADVANCED(Opus_INCLUDE_DIR Opus_LIBRARY)
